package Problems;

/*
 *	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By
 * 	8 starting with 1 and 2, the first 10 terms will be:
 *	
 *	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *	
 *	By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 *	find the sum of the even-valued terms.
 */

public class Fibonacci {

	public static int RunFibonacci(){
		int x1 = 1, x2 = 1, x3;
		int sum = 0;
		
		for(int i = 0; i<31; i++){
			x3 = x1 + x2;
			x2 = x1;
			x1 = x3;
			if(x1%2 == 0) sum += x1;
		}
		
		return sum;
	}

}
